### PR TITLE
Added documentation to the new return types, fixes #861

### LINKED ISSUE #861: Document API return types for types introduced in #859
The api datatypes introduced in #859 need to be annotated with descriptions and examples so that the openapi generated contains meaningful information to users.  At present, the openapi doc produces the following output:

Screenshot 2023-11-02 at 06 32 29

The response type needs annotating to provide details of the response, e.g. something like:

Screenshot 2023-11-02 at 06 32 52

The return classes need annotating ,i.e. : 
https://github.com/Hyperfoil/Horreum/blob/450ab70feaa86fb36992bea57a18e0b944136b80/horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/FingerprintValue.java#L8

needs to be something like:

https://github.com/Hyperfoil/Horreum/blob/450ab70feaa86fb36992bea57a18e0b944136b80/horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/services/TestService.java#L250

### PR DESCRIPTION
**Pull request by stalep**

### CODE REVIEW

**Comment by jesperpedersen** [comment]
```
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManagerRunner] TS2339: Property 'schema' does not exist on type 'LabelValue'.
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManagerRunner]     44 |                 cells: [
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManagerRunner]     45 |                     <React.Fragment key="name">{lv.name}</React.Fragment>,
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManagerRunner]   > 46 |                     <NavLink key="schema" to={`/schema/${lv.schema.id}#labels+${encodeURIComponent(lv.name)}`}>
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManagerRunner]        |                                                             ^^^^^^
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManagerRunner]     47 |                         {lv.schema.name} (<code>{lv.schema.uri}</code>)
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManagerRunner]     48 |                     </NavLink>,
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManagerRunner]     49 |                     <pre key="value">
```

**Comment by stalep** [comment]
This seems to be caused by a class name conflict with the data type we return from DatasetServiceImpl.labelValues. I'll rename the newly created objects.

**Comment by jesperpedersen** [comment]
Rebased, and merged.

Thanks for your contribution !
